(define (problem coloriage)
(:domain coloriage)
(:objects n1 n2 n4 n3 - noeud
                a1 a2 a3 a4 - arrete
                c1 c2 c3 - color)
        (:init
                (voisin n1 n2)
                (voisin n2 n1)
                (voisin n2 n3)
                (voisin n3 n2)
                (voisin n3 n4)
                (voisin n4 n3)
                (voisin n4 n2)
                (voisin n2 n4)
                (incolore n1)
                (incolore n2)
                (incolore n3)
                (incolore n4)
                (differentes_couleurs c1 c2)
                (differentes_couleurs c2 c1)
                (differentes_couleurs c1 c3)
                (differentes_couleurs c3 c1)
                (differentes_couleurs c2 c3)
                (differentes_couleurs c3 c2)
                (entre a1 n1 n2)
                (entre a1 n2 n1)
                (entre a2 n2 n3)
                (entre a2 n3 n2)
                (entre a3 n3 n4)
                (entre a3 n4 n3)
                (entre a4 n4 n2)
                )
        (:goal (and (marquee a1)(marquee a2)(marquee a3)(marquee a4)))
)
