(define (problem pursuit-evasion-4-0)
(:domain pursuit-evasion)
(:objects n1 n2 n3 n4 n5 - noeud 
          e1 e2 e3 e4 e5 - arrete
          a1 a2 - agent)

(:init (different a1 a2)
        (voisin n1 n2) 
        (voisin n2 n1) 
        (voisin n2 n3) 
        (voisin n3 n2) 
        (voisin n2 n4)
        (voisin n4 n2)
        (voisin n2 n5)
        (voisin n5 n2)
        (voisin n5 n4)
        (voisin n4 n5)
        (estEntre n1 n2 e1)
        (estEntre n2 n1 e1)
        (estEntre n2 n3 e2)
        (estEntre n3 n2 e2)
        (estEntre n2 n4 e3)
        (estEntre n4 n2 e3)
        (estEntre n2 n5 e4)
        (estEntre n5 n2 e4)
        (estEntre n4 n5 e5)
        (estEntre n5 n4 e5)
        (agentSur a1 n1)
        (agentSur a2 n1)
        (visite n1)
        (contamine e1)
        (contamine e2)
        (contamine e3)
        (contamine e4)
        (contamine e5)
        (agentSur a1 n1)
        (agentSur a2 n1)
        (sortieunique  n1 e1)
        (sortieunique  n3 e2)
)

(:goal (and (decontamine e1) 
            (decontamine e2)
            (decontamine e3)
            (decontamine e4)
            (decontamine e5)
            
        )
    )
)
